title: NAFO Armories
description: That one group of crazy doggos making [redacted]
email: your-email@example.com
baseurl: ""
url: "https://nafoarmories.org"
twitter_username: nafoarmories
github_username:  nafoarmories

#theme: minima
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
